## act 101 (act1/101): 경기 시작(700) 전까지의 예약 명령을 순서대로 재생하고 700로 옮긴다
execute if score .act global matches 101 if score .seq global matches ..0 run scoreboard players set .seq global 0
execute if score .act global matches 101 if score .seq global matches 0 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..1 run scoreboard players set .seq global 1
execute if score .act global matches 101 if score .seq global matches 1 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..2 run scoreboard players set .seq global 2
execute if score .act global matches 101 if score .seq global matches 2 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..20 run scoreboard players set .seq global 20
execute if score .act global matches 101 if score .seq global matches 20 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..21 run scoreboard players set .seq global 21
execute if score .act global matches 101 if score .seq global matches 21 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..40 run scoreboard players set .seq global 40
execute if score .act global matches 101 if score .seq global matches 40 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..140 run scoreboard players set .seq global 140
execute if score .act global matches 101 if score .seq global matches 140 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..200 run scoreboard players set .seq global 200
execute if score .act global matches 101 if score .seq global matches 200 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..219 run scoreboard players set .seq global 219
execute if score .act global matches 101 if score .seq global matches 219 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..220 run scoreboard players set .seq global 220
execute if score .act global matches 101 if score .seq global matches 220 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..280 run scoreboard players set .seq global 280
execute if score .act global matches 101 if score .seq global matches 280 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..340 run scoreboard players set .seq global 340
execute if score .act global matches 101 if score .seq global matches 340 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..400 run scoreboard players set .seq global 400
execute if score .act global matches 101 if score .seq global matches 400 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..460 run scoreboard players set .seq global 460
execute if score .act global matches 101 if score .seq global matches 460 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..520 run scoreboard players set .seq global 520
execute if score .act global matches 101 if score .seq global matches 520 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..580 run scoreboard players set .seq global 580
execute if score .act global matches 101 if score .seq global matches 580 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..600 run scoreboard players set .seq global 600
execute if score .act global matches 101 if score .seq global matches 600 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..601 run scoreboard players set .seq global 601
execute if score .act global matches 101 if score .seq global matches 601 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..640 run scoreboard players set .seq global 640
execute if score .act global matches 101 if score .seq global matches 640 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..660 run scoreboard players set .seq global 660
execute if score .act global matches 101 if score .seq global matches 660 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..680 run scoreboard players set .seq global 680
execute if score .act global matches 101 if score .seq global matches 680 as @p at @s run function seq/act1/101
execute if score .act global matches 101 if score .seq global matches ..700 run scoreboard players set .seq global 700
