## act 202 (act2/202): 경기 시작(2200) 전까지의 예약 명령을 순서대로 재생하고 2200로 옮긴다
execute if score .act global matches 202 if score .seq global matches ..0 run scoreboard players set .seq global 0
execute if score .act global matches 202 if score .seq global matches 0 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1 run scoreboard players set .seq global 1
execute if score .act global matches 202 if score .seq global matches 1 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..2 run scoreboard players set .seq global 2
execute if score .act global matches 202 if score .seq global matches 2 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..10 run scoreboard players set .seq global 10
execute if score .act global matches 202 if score .seq global matches 10 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..20 run scoreboard players set .seq global 20
execute if score .act global matches 202 if score .seq global matches 20 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..21 run scoreboard players set .seq global 21
execute if score .act global matches 202 if score .seq global matches 21 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..100 run scoreboard players set .seq global 100
execute if score .act global matches 202 if score .seq global matches 100 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..120 run scoreboard players set .seq global 120
execute if score .act global matches 202 if score .seq global matches 120 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..140 run scoreboard players set .seq global 140
execute if score .act global matches 202 if score .seq global matches 140 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..160 run scoreboard players set .seq global 160
execute if score .act global matches 202 if score .seq global matches 160 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..180 run scoreboard players set .seq global 180
execute if score .act global matches 202 if score .seq global matches 180 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..200 run scoreboard players set .seq global 200
execute if score .act global matches 202 if score .seq global matches 200 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..220 run scoreboard players set .seq global 220
execute if score .act global matches 202 if score .seq global matches 220 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..221 run scoreboard players set .seq global 221
execute if score .act global matches 202 if score .seq global matches 221 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..320 run scoreboard players set .seq global 320
execute if score .act global matches 202 if score .seq global matches 320 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..341 run scoreboard players set .seq global 341
execute if score .act global matches 202 if score .seq global matches 341 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..420 run scoreboard players set .seq global 420
execute if score .act global matches 202 if score .seq global matches 420 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..461 run scoreboard players set .seq global 461
execute if score .act global matches 202 if score .seq global matches 461 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..470 run scoreboard players set .seq global 470
execute if score .act global matches 202 if score .seq global matches 470 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..520 run scoreboard players set .seq global 520
execute if score .act global matches 202 if score .seq global matches 520 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..560 run scoreboard players set .seq global 560
execute if score .act global matches 202 if score .seq global matches 560 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..620 run scoreboard players set .seq global 620
execute if score .act global matches 202 if score .seq global matches 620 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..661 run scoreboard players set .seq global 661
execute if score .act global matches 202 if score .seq global matches 661 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..700 run scoreboard players set .seq global 700
execute if score .act global matches 202 if score .seq global matches 700 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..720 run scoreboard players set .seq global 720
execute if score .act global matches 202 if score .seq global matches 720 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..740 run scoreboard players set .seq global 740
execute if score .act global matches 202 if score .seq global matches 740 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..760 run scoreboard players set .seq global 760
execute if score .act global matches 202 if score .seq global matches 760 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..780 run scoreboard players set .seq global 780
execute if score .act global matches 202 if score .seq global matches 780 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..800 run scoreboard players set .seq global 800
execute if score .act global matches 202 if score .seq global matches 800 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..820 run scoreboard players set .seq global 820
execute if score .act global matches 202 if score .seq global matches 820 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..840 run scoreboard players set .seq global 840
execute if score .act global matches 202 if score .seq global matches 840 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..860 run scoreboard players set .seq global 860
execute if score .act global matches 202 if score .seq global matches 860 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..861 run scoreboard players set .seq global 861
execute if score .act global matches 202 if score .seq global matches 861 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..880 run scoreboard players set .seq global 880
execute if score .act global matches 202 if score .seq global matches 880 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1000 run scoreboard players set .seq global 1000
execute if score .act global matches 202 if score .seq global matches 1000 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1061 run scoreboard players set .seq global 1061
execute if score .act global matches 202 if score .seq global matches 1061 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1120 run scoreboard players set .seq global 1120
execute if score .act global matches 202 if score .seq global matches 1120 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1121 run scoreboard players set .seq global 1121
execute if score .act global matches 202 if score .seq global matches 1121 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1122 run scoreboard players set .seq global 1122
execute if score .act global matches 202 if score .seq global matches 1122 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1123 run scoreboard players set .seq global 1123
execute if score .act global matches 202 if score .seq global matches 1123 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1140 run scoreboard players set .seq global 1140
execute if score .act global matches 202 if score .seq global matches 1140 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1261 run scoreboard players set .seq global 1261
execute if score .act global matches 202 if score .seq global matches 1261 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1280 run scoreboard players set .seq global 1280
execute if score .act global matches 202 if score .seq global matches 1280 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1400 run scoreboard players set .seq global 1400
execute if score .act global matches 202 if score .seq global matches 1400 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1461 run scoreboard players set .seq global 1461
execute if score .act global matches 202 if score .seq global matches 1461 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1500 run scoreboard players set .seq global 1500
execute if score .act global matches 202 if score .seq global matches 1500 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1561 run scoreboard players set .seq global 1561
execute if score .act global matches 202 if score .seq global matches 1561 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1700 run scoreboard players set .seq global 1700
execute if score .act global matches 202 if score .seq global matches 1700 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1720 run scoreboard players set .seq global 1720
execute if score .act global matches 202 if score .seq global matches 1720 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1740 run scoreboard players set .seq global 1740
execute if score .act global matches 202 if score .seq global matches 1740 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1760 run scoreboard players set .seq global 1760
execute if score .act global matches 202 if score .seq global matches 1760 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1761 run scoreboard players set .seq global 1761
execute if score .act global matches 202 if score .seq global matches 1761 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1780 run scoreboard players set .seq global 1780
execute if score .act global matches 202 if score .seq global matches 1780 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1820 run scoreboard players set .seq global 1820
execute if score .act global matches 202 if score .seq global matches 1820 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..1900 run scoreboard players set .seq global 1900
execute if score .act global matches 202 if score .seq global matches 1900 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..2030 run scoreboard players set .seq global 2030
execute if score .act global matches 202 if score .seq global matches 2030 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..2040 run scoreboard players set .seq global 2040
execute if score .act global matches 202 if score .seq global matches 2040 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..2060 run scoreboard players set .seq global 2060
execute if score .act global matches 202 if score .seq global matches 2060 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..2062 run scoreboard players set .seq global 2062
execute if score .act global matches 202 if score .seq global matches 2062 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..2120 run scoreboard players set .seq global 2120
execute if score .act global matches 202 if score .seq global matches 2120 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..2140 run scoreboard players set .seq global 2140
execute if score .act global matches 202 if score .seq global matches 2140 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..2160 run scoreboard players set .seq global 2160
execute if score .act global matches 202 if score .seq global matches 2160 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..2180 run scoreboard players set .seq global 2180
execute if score .act global matches 202 if score .seq global matches 2180 as @p at @s run function seq/act2/202
execute if score .act global matches 202 if score .seq global matches ..2200 run scoreboard players set .seq global 2200
