## act 501 (act5/501): 경기 시작(1160) 전까지의 예약 명령을 순서대로 재생하고 1160로 옮긴다
execute if score .act global matches 501 if score .seq global matches ..0 run scoreboard players set .seq global 0
execute if score .act global matches 501 if score .seq global matches 0 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..1 run scoreboard players set .seq global 1
execute if score .act global matches 501 if score .seq global matches 1 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..2 run scoreboard players set .seq global 2
execute if score .act global matches 501 if score .seq global matches 2 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..20 run scoreboard players set .seq global 20
execute if score .act global matches 501 if score .seq global matches 20 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..21 run scoreboard players set .seq global 21
execute if score .act global matches 501 if score .seq global matches 21 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..40 run scoreboard players set .seq global 40
execute if score .act global matches 501 if score .seq global matches 40 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..100 run scoreboard players set .seq global 100
execute if score .act global matches 501 if score .seq global matches 100 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..220 run scoreboard players set .seq global 220
execute if score .act global matches 501 if score .seq global matches 220 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..321 run scoreboard players set .seq global 321
execute if score .act global matches 501 if score .seq global matches 321 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..340 run scoreboard players set .seq global 340
execute if score .act global matches 501 if score .seq global matches 340 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..440 run scoreboard players set .seq global 440
execute if score .act global matches 501 if score .seq global matches 440 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..521 run scoreboard players set .seq global 521
execute if score .act global matches 501 if score .seq global matches 521 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..660 run scoreboard players set .seq global 660
execute if score .act global matches 501 if score .seq global matches 660 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..700 run scoreboard players set .seq global 700
execute if score .act global matches 501 if score .seq global matches 700 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..721 run scoreboard players set .seq global 721
execute if score .act global matches 501 if score .seq global matches 721 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..800 run scoreboard players set .seq global 800
execute if score .act global matches 501 if score .seq global matches 800 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..900 run scoreboard players set .seq global 900
execute if score .act global matches 501 if score .seq global matches 900 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..1030 run scoreboard players set .seq global 1030
execute if score .act global matches 501 if score .seq global matches 1030 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..1060 run scoreboard players set .seq global 1060
execute if score .act global matches 501 if score .seq global matches 1060 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..1061 run scoreboard players set .seq global 1061
execute if score .act global matches 501 if score .seq global matches 1061 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..1062 run scoreboard players set .seq global 1062
execute if score .act global matches 501 if score .seq global matches 1062 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..1100 run scoreboard players set .seq global 1100
execute if score .act global matches 501 if score .seq global matches 1100 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..1120 run scoreboard players set .seq global 1120
execute if score .act global matches 501 if score .seq global matches 1120 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..1140 run scoreboard players set .seq global 1140
execute if score .act global matches 501 if score .seq global matches 1140 as @p at @s run function seq/act5/501
execute if score .act global matches 501 if score .seq global matches ..1160 run scoreboard players set .seq global 1160
