## act 601 (act6/601): 경기 시작(1000) 전까지의 예약 명령을 순서대로 재생하고 1000로 옮긴다
execute if score .act global matches 601 if score .seq global matches ..0 run scoreboard players set .seq global 0
execute if score .act global matches 601 if score .seq global matches 0 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..1 run scoreboard players set .seq global 1
execute if score .act global matches 601 if score .seq global matches 1 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2 run scoreboard players set .seq global 2
execute if score .act global matches 601 if score .seq global matches 2 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..20 run scoreboard players set .seq global 20
execute if score .act global matches 601 if score .seq global matches 20 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..21 run scoreboard players set .seq global 21
execute if score .act global matches 601 if score .seq global matches 21 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..40 run scoreboard players set .seq global 40
execute if score .act global matches 601 if score .seq global matches 40 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..120 run scoreboard players set .seq global 120
execute if score .act global matches 601 if score .seq global matches 120 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..260 run scoreboard players set .seq global 260
execute if score .act global matches 601 if score .seq global matches 260 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..430 run scoreboard players set .seq global 430
execute if score .act global matches 601 if score .seq global matches 430 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..520 run scoreboard players set .seq global 520
execute if score .act global matches 601 if score .seq global matches 520 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..600 run scoreboard players set .seq global 600
execute if score .act global matches 601 if score .seq global matches 600 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..660 run scoreboard players set .seq global 660
execute if score .act global matches 601 if score .seq global matches 660 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..721 run scoreboard players set .seq global 721
execute if score .act global matches 601 if score .seq global matches 721 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..820 run scoreboard players set .seq global 820
execute if score .act global matches 601 if score .seq global matches 820 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..900 run scoreboard players set .seq global 900
execute if score .act global matches 601 if score .seq global matches 900 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..915 run scoreboard players set .seq global 915
execute if score .act global matches 601 if score .seq global matches 915 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..940 run scoreboard players set .seq global 940
execute if score .act global matches 601 if score .seq global matches 940 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..960 run scoreboard players set .seq global 960
execute if score .act global matches 601 if score .seq global matches 960 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..980 run scoreboard players set .seq global 980
execute if score .act global matches 601 if score .seq global matches 980 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..1000 run scoreboard players set .seq global 1000
