## act 401: 로비 복귀(4280)까지 재생, 승패 판정(4170)은 건너뜀
execute if score .act global matches 401 if score .seq global matches ..0 run scoreboard players set .seq global 0
execute if score .act global matches 401 if score .seq global matches 0 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..1 run scoreboard players set .seq global 1
execute if score .act global matches 401 if score .seq global matches 1 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..2 run scoreboard players set .seq global 2
execute if score .act global matches 401 if score .seq global matches 2 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..5 run scoreboard players set .seq global 5
execute if score .act global matches 401 if score .seq global matches 5 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..10 run scoreboard players set .seq global 10
execute if score .act global matches 401 if score .seq global matches 10 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..20 run scoreboard players set .seq global 20
execute if score .act global matches 401 if score .seq global matches 20 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..21 run scoreboard players set .seq global 21
execute if score .act global matches 401 if score .seq global matches 21 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..100 run scoreboard players set .seq global 100
execute if score .act global matches 401 if score .seq global matches 100 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..200 run scoreboard players set .seq global 200
execute if score .act global matches 401 if score .seq global matches 200 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..221 run scoreboard players set .seq global 221
execute if score .act global matches 401 if score .seq global matches 221 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..300 run scoreboard players set .seq global 300
execute if score .act global matches 401 if score .seq global matches 300 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..381 run scoreboard players set .seq global 381
execute if score .act global matches 401 if score .seq global matches 381 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..440 run scoreboard players set .seq global 440
execute if score .act global matches 401 if score .seq global matches 440 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..480 run scoreboard players set .seq global 480
execute if score .act global matches 401 if score .seq global matches 480 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..490 run scoreboard players set .seq global 490
execute if score .act global matches 401 if score .seq global matches 490 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..500 run scoreboard players set .seq global 500
execute if score .act global matches 401 if score .seq global matches 500 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..510 run scoreboard players set .seq global 510
execute if score .act global matches 401 if score .seq global matches 510 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..511 run scoreboard players set .seq global 511
execute if score .act global matches 401 if score .seq global matches 511 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..512 run scoreboard players set .seq global 512
execute if score .act global matches 401 if score .seq global matches 512 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..540 run scoreboard players set .seq global 540
execute if score .act global matches 401 if score .seq global matches 540 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..560 run scoreboard players set .seq global 560
execute if score .act global matches 401 if score .seq global matches 560 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..580 run scoreboard players set .seq global 580
execute if score .act global matches 401 if score .seq global matches 580 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..600 run scoreboard players set .seq global 600
execute if score .act global matches 401 if score .seq global matches 600 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..4160 run scoreboard players set .seq global 4160
execute if score .act global matches 401 if score .seq global matches 4160 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..4240 run scoreboard players set .seq global 4240
execute if score .act global matches 401 if score .seq global matches 4240 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..4250 run scoreboard players set .seq global 4250
execute if score .act global matches 401 if score .seq global matches 4250 as @p at @s run function seq/act4/401
execute if score .act global matches 401 if score .seq global matches ..4280 run scoreboard players set .seq global 4280
execute if score .act global matches 401 if score .seq global matches 4280 as @p at @s run function seq/act4/401
