## act 601: 로비 복귀(2660)까지 재생, 승패 판정(2380)은 건너뜀
execute if score .act global matches 601 if score .seq global matches ..0 run scoreboard players set .seq global 0
execute if score .act global matches 601 if score .seq global matches 0 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..1 run scoreboard players set .seq global 1
execute if score .act global matches 601 if score .seq global matches 1 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2 run scoreboard players set .seq global 2
execute if score .act global matches 601 if score .seq global matches 2 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..20 run scoreboard players set .seq global 20
execute if score .act global matches 601 if score .seq global matches 20 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..21 run scoreboard players set .seq global 21
execute if score .act global matches 601 if score .seq global matches 21 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..40 run scoreboard players set .seq global 40
execute if score .act global matches 601 if score .seq global matches 40 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..120 run scoreboard players set .seq global 120
execute if score .act global matches 601 if score .seq global matches 120 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..260 run scoreboard players set .seq global 260
execute if score .act global matches 601 if score .seq global matches 260 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..430 run scoreboard players set .seq global 430
execute if score .act global matches 601 if score .seq global matches 430 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..520 run scoreboard players set .seq global 520
execute if score .act global matches 601 if score .seq global matches 520 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..600 run scoreboard players set .seq global 600
execute if score .act global matches 601 if score .seq global matches 600 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..660 run scoreboard players set .seq global 660
execute if score .act global matches 601 if score .seq global matches 660 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..721 run scoreboard players set .seq global 721
execute if score .act global matches 601 if score .seq global matches 721 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..820 run scoreboard players set .seq global 820
execute if score .act global matches 601 if score .seq global matches 820 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..900 run scoreboard players set .seq global 900
execute if score .act global matches 601 if score .seq global matches 900 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..915 run scoreboard players set .seq global 915
execute if score .act global matches 601 if score .seq global matches 915 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..940 run scoreboard players set .seq global 940
execute if score .act global matches 601 if score .seq global matches 940 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..960 run scoreboard players set .seq global 960
execute if score .act global matches 601 if score .seq global matches 960 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..980 run scoreboard players set .seq global 980
execute if score .act global matches 601 if score .seq global matches 980 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..1000 run scoreboard players set .seq global 1000
execute if score .act global matches 601 if score .seq global matches 1000 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..1001 run scoreboard players set .seq global 1001
execute if score .act global matches 601 if score .seq global matches 1001 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2301 run scoreboard players set .seq global 2301
execute if score .act global matches 601 if score .seq global matches 2301 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2320 run scoreboard players set .seq global 2320
execute if score .act global matches 601 if score .seq global matches 2320 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2321 run scoreboard players set .seq global 2321
execute if score .act global matches 601 if score .seq global matches 2321 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2322 run scoreboard players set .seq global 2322
execute if score .act global matches 601 if score .seq global matches 2322 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2325 run scoreboard players set .seq global 2325
execute if score .act global matches 601 if score .seq global matches 2325 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2326 run scoreboard players set .seq global 2326
execute if score .act global matches 601 if score .seq global matches 2326 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2327 run scoreboard players set .seq global 2327
execute if score .act global matches 601 if score .seq global matches 2327 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2328 run scoreboard players set .seq global 2328
execute if score .act global matches 601 if score .seq global matches 2328 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2330 run scoreboard players set .seq global 2330
execute if score .act global matches 601 if score .seq global matches 2330 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2331 run scoreboard players set .seq global 2331
execute if score .act global matches 601 if score .seq global matches 2331 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2620 run scoreboard players set .seq global 2620
execute if score .act global matches 601 if score .seq global matches 2620 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2630 run scoreboard players set .seq global 2630
execute if score .act global matches 601 if score .seq global matches 2630 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2639 run scoreboard players set .seq global 2639
execute if score .act global matches 601 if score .seq global matches 2639 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2640 run scoreboard players set .seq global 2640
execute if score .act global matches 601 if score .seq global matches 2640 as @p at @s run function seq/act6/601
execute if score .act global matches 601 if score .seq global matches ..2660 run scoreboard players set .seq global 2660
execute if score .act global matches 601 if score .seq global matches 2660 as @p at @s run function seq/act6/601
