## act 301: 로비 복귀(7380)까지 재생, 승패 판정(7290)은 건너뜀
execute if score .act global matches 301 if score .seq global matches ..0 run scoreboard players set .seq global 0
execute if score .act global matches 301 if score .seq global matches 0 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..1 run scoreboard players set .seq global 1
execute if score .act global matches 301 if score .seq global matches 1 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..2 run scoreboard players set .seq global 2
execute if score .act global matches 301 if score .seq global matches 2 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..20 run scoreboard players set .seq global 20
execute if score .act global matches 301 if score .seq global matches 20 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..21 run scoreboard players set .seq global 21
execute if score .act global matches 301 if score .seq global matches 21 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..100 run scoreboard players set .seq global 100
execute if score .act global matches 301 if score .seq global matches 100 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..261 run scoreboard players set .seq global 261
execute if score .act global matches 301 if score .seq global matches 261 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..300 run scoreboard players set .seq global 300
execute if score .act global matches 301 if score .seq global matches 300 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..302 run scoreboard players set .seq global 302
execute if score .act global matches 301 if score .seq global matches 302 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..401 run scoreboard players set .seq global 401
execute if score .act global matches 301 if score .seq global matches 401 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..500 run scoreboard players set .seq global 500
execute if score .act global matches 301 if score .seq global matches 500 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..560 run scoreboard players set .seq global 560
execute if score .act global matches 301 if score .seq global matches 560 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..561 run scoreboard players set .seq global 561
execute if score .act global matches 301 if score .seq global matches 561 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..600 run scoreboard players set .seq global 600
execute if score .act global matches 301 if score .seq global matches 600 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..700 run scoreboard players set .seq global 700
execute if score .act global matches 301 if score .seq global matches 700 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..720 run scoreboard players set .seq global 720
execute if score .act global matches 301 if score .seq global matches 720 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..741 run scoreboard players set .seq global 741
execute if score .act global matches 301 if score .seq global matches 741 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..850 run scoreboard players set .seq global 850
execute if score .act global matches 301 if score .seq global matches 850 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..880 run scoreboard players set .seq global 880
execute if score .act global matches 301 if score .seq global matches 880 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..910 run scoreboard players set .seq global 910
execute if score .act global matches 301 if score .seq global matches 910 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..912 run scoreboard players set .seq global 912
execute if score .act global matches 301 if score .seq global matches 912 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..921 run scoreboard players set .seq global 921
execute if score .act global matches 301 if score .seq global matches 921 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..980 run scoreboard players set .seq global 980
execute if score .act global matches 301 if score .seq global matches 980 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..1040 run scoreboard players set .seq global 1040
execute if score .act global matches 301 if score .seq global matches 1040 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..1060 run scoreboard players set .seq global 1060
execute if score .act global matches 301 if score .seq global matches 1060 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..1061 run scoreboard players set .seq global 1061
execute if score .act global matches 301 if score .seq global matches 1061 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..1100 run scoreboard players set .seq global 1100
execute if score .act global matches 301 if score .seq global matches 1100 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..1120 run scoreboard players set .seq global 1120
execute if score .act global matches 301 if score .seq global matches 1120 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..1140 run scoreboard players set .seq global 1140
execute if score .act global matches 301 if score .seq global matches 1140 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..1160 run scoreboard players set .seq global 1160
execute if score .act global matches 301 if score .seq global matches 1160 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..7280 run scoreboard players set .seq global 7280
execute if score .act global matches 301 if score .seq global matches 7280 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..7281 run scoreboard players set .seq global 7281
execute if score .act global matches 301 if score .seq global matches 7281 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..7360 run scoreboard players set .seq global 7360
execute if score .act global matches 301 if score .seq global matches 7360 as @p at @s run function seq/act3/301
execute if score .act global matches 301 if score .seq global matches ..7380 run scoreboard players set .seq global 7380
execute if score .act global matches 301 if score .seq global matches 7380 as @p at @s run function seq/act3/301
