## act 201: 로비 복귀(7600)까지 재생, 승패 판정(7210)은 건너뜀
execute if score .act global matches 201 if score .seq global matches ..0 run scoreboard players set .seq global 0
execute if score .act global matches 201 if score .seq global matches 0 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..1 run scoreboard players set .seq global 1
execute if score .act global matches 201 if score .seq global matches 1 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..2 run scoreboard players set .seq global 2
execute if score .act global matches 201 if score .seq global matches 2 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..10 run scoreboard players set .seq global 10
execute if score .act global matches 201 if score .seq global matches 10 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..20 run scoreboard players set .seq global 20
execute if score .act global matches 201 if score .seq global matches 20 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..21 run scoreboard players set .seq global 21
execute if score .act global matches 201 if score .seq global matches 21 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..100 run scoreboard players set .seq global 100
execute if score .act global matches 201 if score .seq global matches 100 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..120 run scoreboard players set .seq global 120
execute if score .act global matches 201 if score .seq global matches 120 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..140 run scoreboard players set .seq global 140
execute if score .act global matches 201 if score .seq global matches 140 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..160 run scoreboard players set .seq global 160
execute if score .act global matches 201 if score .seq global matches 160 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..180 run scoreboard players set .seq global 180
execute if score .act global matches 201 if score .seq global matches 180 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..220 run scoreboard players set .seq global 220
execute if score .act global matches 201 if score .seq global matches 220 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..221 run scoreboard players set .seq global 221
execute if score .act global matches 201 if score .seq global matches 221 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..420 run scoreboard players set .seq global 420
execute if score .act global matches 201 if score .seq global matches 420 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..421 run scoreboard players set .seq global 421
execute if score .act global matches 201 if score .seq global matches 421 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..500 run scoreboard players set .seq global 500
execute if score .act global matches 201 if score .seq global matches 500 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..600 run scoreboard players set .seq global 600
execute if score .act global matches 201 if score .seq global matches 600 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..620 run scoreboard players set .seq global 620
execute if score .act global matches 201 if score .seq global matches 620 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..621 run scoreboard players set .seq global 621
execute if score .act global matches 201 if score .seq global matches 621 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..640 run scoreboard players set .seq global 640
execute if score .act global matches 201 if score .seq global matches 640 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..660 run scoreboard players set .seq global 660
execute if score .act global matches 201 if score .seq global matches 660 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..680 run scoreboard players set .seq global 680
execute if score .act global matches 201 if score .seq global matches 680 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..700 run scoreboard players set .seq global 700
execute if score .act global matches 201 if score .seq global matches 700 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..720 run scoreboard players set .seq global 720
execute if score .act global matches 201 if score .seq global matches 720 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..740 run scoreboard players set .seq global 740
execute if score .act global matches 201 if score .seq global matches 740 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..760 run scoreboard players set .seq global 760
execute if score .act global matches 201 if score .seq global matches 760 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..780 run scoreboard players set .seq global 780
execute if score .act global matches 201 if score .seq global matches 780 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..800 run scoreboard players set .seq global 800
execute if score .act global matches 201 if score .seq global matches 800 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..820 run scoreboard players set .seq global 820
execute if score .act global matches 201 if score .seq global matches 820 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..821 run scoreboard players set .seq global 821
execute if score .act global matches 201 if score .seq global matches 821 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..920 run scoreboard players set .seq global 920
execute if score .act global matches 201 if score .seq global matches 920 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..1000 run scoreboard players set .seq global 1000
execute if score .act global matches 201 if score .seq global matches 1000 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..1020 run scoreboard players set .seq global 1020
execute if score .act global matches 201 if score .seq global matches 1020 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..1021 run scoreboard players set .seq global 1021
execute if score .act global matches 201 if score .seq global matches 1021 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..1030 run scoreboard players set .seq global 1030
execute if score .act global matches 201 if score .seq global matches 1030 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..1040 run scoreboard players set .seq global 1040
execute if score .act global matches 201 if score .seq global matches 1040 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..1060 run scoreboard players set .seq global 1060
execute if score .act global matches 201 if score .seq global matches 1060 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..1062 run scoreboard players set .seq global 1062
execute if score .act global matches 201 if score .seq global matches 1062 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..1140 run scoreboard players set .seq global 1140
execute if score .act global matches 201 if score .seq global matches 1140 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..1160 run scoreboard players set .seq global 1160
execute if score .act global matches 201 if score .seq global matches 1160 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..1180 run scoreboard players set .seq global 1180
execute if score .act global matches 201 if score .seq global matches 1180 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..1200 run scoreboard players set .seq global 1200
execute if score .act global matches 201 if score .seq global matches 1200 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..1950 run scoreboard players set .seq global 1950
execute if score .act global matches 201 if score .seq global matches 1950 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..2700 run scoreboard players set .seq global 2700
execute if score .act global matches 201 if score .seq global matches 2700 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..3450 run scoreboard players set .seq global 3450
execute if score .act global matches 201 if score .seq global matches 3450 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..3900 run scoreboard players set .seq global 3900
execute if score .act global matches 201 if score .seq global matches 3900 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..4200 run scoreboard players set .seq global 4200
execute if score .act global matches 201 if score .seq global matches 4200 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..4950 run scoreboard players set .seq global 4950
execute if score .act global matches 201 if score .seq global matches 4950 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..5700 run scoreboard players set .seq global 5700
execute if score .act global matches 201 if score .seq global matches 5700 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..6450 run scoreboard players set .seq global 6450
execute if score .act global matches 201 if score .seq global matches 6450 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..6600 run scoreboard players set .seq global 6600
execute if score .act global matches 201 if score .seq global matches 6600 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..7200 run scoreboard players set .seq global 7200
execute if score .act global matches 201 if score .seq global matches 7200 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..7220 run scoreboard players set .seq global 7220
execute if score .act global matches 201 if score .seq global matches 7220 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..7280 run scoreboard players set .seq global 7280
execute if score .act global matches 201 if score .seq global matches 7280 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..7300 run scoreboard players set .seq global 7300
execute if score .act global matches 201 if score .seq global matches 7300 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..7310 run scoreboard players set .seq global 7310
execute if score .act global matches 201 if score .seq global matches 7310 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..7311 run scoreboard players set .seq global 7311
execute if score .act global matches 201 if score .seq global matches 7311 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..7540 run scoreboard players set .seq global 7540
execute if score .act global matches 201 if score .seq global matches 7540 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..7560 run scoreboard players set .seq global 7560
execute if score .act global matches 201 if score .seq global matches 7560 as @p at @s run function seq/act2/201
execute if score .act global matches 201 if score .seq global matches ..7600 run scoreboard players set .seq global 7600
execute if score .act global matches 201 if score .seq global matches 7600 as @p at @s run function seq/act2/201
