## Used for Doing Syncing Grid Wars Blocks when affected.

execute if entity @s[tag=grid_block_1a] run tag @e[tag=grid_block_1b] add grid_change
execute if entity @s[tag=grid_block_1b] run tag @e[tag=grid_block_1a] add grid_change
execute if entity @s[tag=grid_block_2a] run tag @e[tag=grid_block_2b] add grid_change
execute if entity @s[tag=grid_block_2b] run tag @e[tag=grid_block_2a] add grid_change
execute if entity @s[tag=grid_block_3a] run tag @e[tag=grid_block_3b] add grid_change
execute if entity @s[tag=grid_block_3b] run tag @e[tag=grid_block_3a] add grid_change
execute if entity @s[tag=grid_block_4a] run tag @e[tag=grid_block_4b] add grid_change
execute if entity @s[tag=grid_block_4b] run tag @e[tag=grid_block_4a] add grid_change
execute if entity @s[tag=grid_block_5a] run tag @e[tag=grid_block_5b] add grid_change
execute if entity @s[tag=grid_block_5b] run tag @e[tag=grid_block_5a] add grid_change
execute if entity @s[tag=grid_block_6a] run tag @e[tag=grid_block_6b] add grid_change
execute if entity @s[tag=grid_block_6b] run tag @e[tag=grid_block_6a] add grid_change
execute if entity @s[tag=grid_block_7a] run tag @e[tag=grid_block_7b] add grid_change
execute if entity @s[tag=grid_block_7b] run tag @e[tag=grid_block_7a] add grid_change
execute if entity @s[tag=grid_block_8a] run tag @e[tag=grid_block_8b] add grid_change
execute if entity @s[tag=grid_block_8b] run tag @e[tag=grid_block_8a] add grid_change
execute if entity @s[tag=grid_block_9a] run tag @e[tag=grid_block_9b] add grid_change
execute if entity @s[tag=grid_block_9b] run tag @e[tag=grid_block_9a] add grid_change
execute if entity @s[tag=grid_block_10a] run tag @e[tag=grid_block_10b] add grid_change
execute if entity @s[tag=grid_block_10b] run tag @e[tag=grid_block_10a] add grid_change
execute if entity @s[tag=grid_block_11a] run tag @e[tag=grid_block_11b] add grid_change
execute if entity @s[tag=grid_block_11b] run tag @e[tag=grid_block_11a] add grid_change
execute if entity @s[tag=grid_block_12a] run tag @e[tag=grid_block_12b] add grid_change
execute if entity @s[tag=grid_block_12b] run tag @e[tag=grid_block_12a] add grid_change
execute if entity @s[tag=grid_block_13a] run tag @e[tag=grid_block_13b] add grid_change
execute if entity @s[tag=grid_block_13b] run tag @e[tag=grid_block_13a] add grid_change
execute if entity @s[tag=grid_block_14a] run tag @e[tag=grid_block_14b] add grid_change
execute if entity @s[tag=grid_block_14b] run tag @e[tag=grid_block_14a] add grid_change
execute if entity @s[tag=grid_block_15a] run tag @e[tag=grid_block_15b] add grid_change
execute if entity @s[tag=grid_block_15b] run tag @e[tag=grid_block_15a] add grid_change
execute if entity @s[tag=grid_block_16a] run tag @e[tag=grid_block_16b] add grid_change
execute if entity @s[tag=grid_block_16b] run tag @e[tag=grid_block_16a] add grid_change

execute if entity @e[tag=grid_block_1a,tag=grid_change] run event entity @e[tag=grid_block_1a,tag=grid_change] rwm:grid_block_blue_stolen
execute if entity @e[tag=grid_block_1b,tag=grid_change] run event entity @e[tag=grid_block_1b,tag=grid_change] rwm:grid_block_blue_stolen
execute if entity @e[tag=grid_block_2a,tag=grid_change] run event entity @e[tag=grid_block_2a,tag=grid_change] rwm:grid_block_blue_stolen
execute if entity @e[tag=grid_block_2b,tag=grid_change] run event entity @e[tag=grid_block_2b,tag=grid_change] rwm:grid_block_blue_stolen
execute if entity @e[tag=grid_block_3a,tag=grid_change] run event entity @e[tag=grid_block_3a,tag=grid_change] rwm:grid_block_blue_stolen
execute if entity @e[tag=grid_block_3b,tag=grid_change] run event entity @e[tag=grid_block_3b,tag=grid_change] rwm:grid_block_blue_stolen
execute if entity @e[tag=grid_block_4a,tag=grid_change] run event entity @e[tag=grid_block_4a,tag=grid_change] rwm:grid_block_blue_stolen
execute if entity @e[tag=grid_block_4b,tag=grid_change] run event entity @e[tag=grid_block_4b,tag=grid_change] rwm:grid_block_blue_stolen
execute if entity @e[tag=grid_block_5a,tag=grid_change] run event entity @e[tag=grid_block_5a,tag=grid_change] rwm:grid_block_magenta_stolen
execute if entity @e[tag=grid_block_5b,tag=grid_change] run event entity @e[tag=grid_block_5b,tag=grid_change] rwm:grid_block_magenta_stolen
execute if entity @e[tag=grid_block_6a,tag=grid_change] run event entity @e[tag=grid_block_6a,tag=grid_change] rwm:grid_block_magenta_stolen
execute if entity @e[tag=grid_block_6b,tag=grid_change] run event entity @e[tag=grid_block_6b,tag=grid_change] rwm:grid_block_magenta_stolen
execute if entity @e[tag=grid_block_7a,tag=grid_change] run event entity @e[tag=grid_block_7a,tag=grid_change] rwm:grid_block_magenta_stolen
execute if entity @e[tag=grid_block_7b,tag=grid_change] run event entity @e[tag=grid_block_7b,tag=grid_change] rwm:grid_block_magenta_stolen
execute if entity @e[tag=grid_block_8a,tag=grid_change] run event entity @e[tag=grid_block_8a,tag=grid_change] rwm:grid_block_magenta_stolen
execute if entity @e[tag=grid_block_8b,tag=grid_change] run event entity @e[tag=grid_block_8b,tag=grid_change] rwm:grid_block_magenta_stolen
execute if entity @e[tag=grid_block_9a,tag=grid_change] run event entity @e[tag=grid_block_9a,tag=grid_change] rwm:grid_block_lime_stolen
execute if entity @e[tag=grid_block_9b,tag=grid_change] run event entity @e[tag=grid_block_9b,tag=grid_change] rwm:grid_block_lime_stolen
execute if entity @e[tag=grid_block_10a,tag=grid_change] run event entity @e[tag=grid_block_10a,tag=grid_change] rwm:grid_block_lime_stolen
execute if entity @e[tag=grid_block_10b,tag=grid_change] run event entity @e[tag=grid_block_10b,tag=grid_change] rwm:grid_block_lime_stolen
execute if entity @e[tag=grid_block_11a,tag=grid_change] run event entity @e[tag=grid_block_11a,tag=grid_change] rwm:grid_block_lime_stolen
execute if entity @e[tag=grid_block_11b,tag=grid_change] run event entity @e[tag=grid_block_11b,tag=grid_change] rwm:grid_block_lime_stolen
execute if entity @e[tag=grid_block_12a,tag=grid_change] run event entity @e[tag=grid_block_12a,tag=grid_change] rwm:grid_block_lime_stolen
execute if entity @e[tag=grid_block_12b,tag=grid_change] run event entity @e[tag=grid_block_12b,tag=grid_change] rwm:grid_block_lime_stolen
execute if entity @e[tag=grid_block_13a,tag=grid_change] run event entity @e[tag=grid_block_13a,tag=grid_change] rwm:grid_block_red_stolen
execute if entity @e[tag=grid_block_13b,tag=grid_change] run event entity @e[tag=grid_block_13b,tag=grid_change] rwm:grid_block_red_stolen
execute if entity @e[tag=grid_block_14a,tag=grid_change] run event entity @e[tag=grid_block_14a,tag=grid_change] rwm:grid_block_red_stolen
execute if entity @e[tag=grid_block_14b,tag=grid_change] run event entity @e[tag=grid_block_14b,tag=grid_change] rwm:grid_block_red_stolen
execute if entity @e[tag=grid_block_15a,tag=grid_change] run event entity @e[tag=grid_block_15a,tag=grid_change] rwm:grid_block_yellow_stolen
execute if entity @e[tag=grid_block_15b,tag=grid_change] run event entity @e[tag=grid_block_15b,tag=grid_change] rwm:grid_block_yellow_stolen
execute if entity @e[tag=grid_block_16a,tag=grid_change] run event entity @e[tag=grid_block_16a,tag=grid_change] rwm:grid_block_yellow_stolen
execute if entity @e[tag=grid_block_16b,tag=grid_change] run event entity @e[tag=grid_block_16b,tag=grid_change] rwm:grid_block_yellow_stolen

tag @e[type=rwm:grid_block] remove grid_change